spring:
  redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        timeout: 30000000
        auth: 123456
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1